### ISSUE TITLE
Please add usage example

### ISSUE THREAD

**Issue by Paxa** [jivesoftware/ansible-confd#1]
Something like this:

---
## Ansible role for [confd](https://github.com/kelseyhightower/confd)

https://galaxy.ansible.com/detail#/role/1455
#### Installation

```
ansible-galaxy install savagegus.confd
```
#### Usage

``` yml
- hosts: all
  vars:
    confd_version: "0.10.0"
  roles:
    - savagegus.confd
```
#### Configuration

| var | default | value |
| --- | --- | --- |
| `confd_version` | `0.4.1` | confd version, full list of versions [confd releases](https://github.com/kelseyhightower/confd/releases) |
| `confd_home` | `/usr/bin/` | path to install confd |
| `confd_config` | `/etc/confd` | config folder |
